name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Install linters
        run: |
          go install golang.org/x/lint/golint@latest
          go install github.com/client9/misspell/cmd/misspell@latest

      - name: Run linters
        run: |
          golint ./...
          misspell -error **/*.go
